apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql56-pv-claim
  namespace: kube-mysql56
  labels:
    app: mysql56
    tier: database
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi