apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql56
  namespace: kube-mysql56
  labels:
    app: mysql56
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql56
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql56
        tier: database
    spec:
      containers:
      - image: mysql:5.6
        name: mysql56
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-mysql56-root-credentials
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-mysql-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-mysql-credentials
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-mysql56-config
              key: name
        ports:
        - containerPort: 3306
          name: mysql56
        volumeMounts:
        - name: mysql56-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql56-persistent-storage
        persistentVolumeClaim:
          claimName: mysql56-pv-claim