apiVersion: v1
kind: Service
metadata:
  name: mysql56
  namespace: kube-mysql56
  labels:
    app: mysql56
    tier: database
spec:
  ports:
  - nodePort: 30007
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql56
    tier: database
  type: NodePort