apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql57
  namespace: kube-mysql57
  labels:
    app: mysql57
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql57
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql57
        tier: database
    spec:
      containers:
      - image: mysql:5.7
        name: mysql57
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-mysql-root-credentials
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-mysql-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-mysql-credentials
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-mysql57-config
              key: name
        ports:
        - containerPort: 3306
          name: mysql57
        volumeMounts:
        - name: mysql57-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql57-persistent-storage
        persistentVolumeClaim:
          claimName: mysql57-pv-claim