apiVersion: v1
kind: Service
metadata:
  name: mysql57
  namespace: kube-mysql57
  labels:
    app: mysql57
    tier: database
spec:
  ports:
  - nodePort: 30006
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql57
    tier: database
  type: NodePort