apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql57-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 70Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data/mysql57"