apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql57-pv-claim
  namespace: kube-mysql57
  labels:
    app: mysql57
    tier: database
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 70Gi